<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\CountryCodes;
use DB;

class CountryCodesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('country_codes')->delete();
        CountryCodes::insert([
            array('id' => '1','code' => 'US','country' => 'USA','phone_name' => 'USA (+1)','phone_code' => '1'),
            array('id' => '2','code' => 'DZ','country' => 'Algeria','phone_name' => 'Algeria (+213)','phone_code' => '213'),
            array('id' => '3','code' => 'AD','country' => 'Andorra','phone_name' => 'Andorra (+376)','phone_code' => '376'),
            array('id' => '4','code' => 'AO','country' => 'Angola','phone_name' => 'Angola (+244)','phone_code' => '244'),
            array('id' => '5','code' => 'AI','country' => 'Anguilla','phone_name' => 'Anguilla (+1264)','phone_code' => '1264'),
            array('id' => '6','code' => 'AG','country' => 'Antigua & Barbuda','phone_name' => 'Antigua & Barbuda (+1268)','phone_code' => '1268'),
            array('id' => '7','code' => 'AR','country' => 'Argentina','phone_name' => 'Argentina (+54)','phone_code' => '54'),
            array('id' => '8','code' => 'AM','country' => 'Armenia','phone_name' => 'Armenia (+374)','phone_code' => '374'),
            array('id' => '9','code' => 'AW','country' => 'Aruba','phone_name' => 'Aruba (+297)','phone_code' => '297'),
            array('id' => '10','code' => 'AU','country' => 'Australia','phone_name' => 'Australia (+61)','phone_code' => '61'),
            array('id' => '11','code' => 'AT','country' => 'Austria','phone_name' => 'Austria (+43)','phone_code' => '43'),
            array('id' => '12','code' => 'AZ','country' => 'Azerbaijan','phone_name' => 'Azerbaijan (+994)','phone_code' => '994'),
            array('id' => '13','code' => 'BS','country' => 'Bahamas','phone_name' => 'Bahamas (+1242)','phone_code' => '1242'),
            array('id' => '14','code' => 'BH','country' => 'Bahrain','phone_name' => 'Bahrain (+973)','phone_code' => '973'),
            array('id' => '15','code' => 'BD','country' => 'Bangladesh','phone_name' => 'Bangladesh (+880)','phone_code' => '880'),
            array('id' => '16','code' => 'BB','country' => 'Barbados','phone_name' => 'Barbados (+1246)','phone_code' => '1246'),
            array('id' => '17','code' => 'BY','country' => 'Belarus','phone_name' => 'Belarus (+375)','phone_code' => '375'),
            array('id' => '18','code' => 'BE','country' => 'Belgium','phone_name' => 'Belgium (+32)','phone_code' => '32'),
            array('id' => '19','code' => 'BZ','country' => 'Belize','phone_name' => 'Belize (+501)','phone_code' => '501'),
            array('id' => '20','code' => 'BJ','country' => 'Benin','phone_name' => 'Benin (+229)','phone_code' => '229'),
            array('id' => '21','code' => 'BM','country' => 'Bermuda','phone_name' => 'Bermuda (+1441)','phone_code' => '1441'),
            array('id' => '22','code' => 'BT','country' => 'Bhutan','phone_name' => 'Bhutan (+975)','phone_code' => '975'),
            array('id' => '23','code' => 'BO','country' => 'Bolivia','phone_name' => 'Bolivia (+591)','phone_code' => '591'),
            array('id' => '24','code' => 'BA','country' => 'Bosnia Herzegovina','phone_name' => 'Bosnia Herzegovina (+387)','phone_code' => '378'),
            array('id' => '25','code' => 'BW','country' => 'Botswana','phone_name' => 'Botswana (+267)','phone_code' => '267'),
            array('id' => '26','code' => 'BR','country' => 'Brazil','phone_name' => 'Brazil (+55)','phone_code' => '55'),
            array('id' => '27','code' => 'BN','country' => 'Brunei','phone_name' => 'Brunei (+673)','phone_code' => '673'),
            array('id' => '28','code' => 'BG','country' => 'Bulgaria','phone_name' => 'Bulgaria (+359)','phone_code' => '359'),
            array('id' => '29','code' => 'BF','country' => 'Burkina Faso','phone_name' => 'Burkina Faso (+226)','phone_code' => '226'),
            array('id' => '30','code' => 'BI','country' => 'Burundi','phone_name' => 'Burundi (+257)','phone_code' => '257'),
            array('id' => '31','code' => 'KH','country' => 'Cambodia','phone_name' => 'Cambodia (+855)','phone_code' => '855'),
            array('id' => '32','code' => 'CM','country' => 'Cameroon','phone_name' => 'Cameroon (+237)','phone_code' => '237'),
            array('id' => '33','code' => 'CA','country' => 'Canada','phone_name' => 'Canada (+1)','phone_code' => '1'),
            array('id' => '34','code' => 'CV','country' => 'Cape Verde Islands','phone_name' => 'Cape Verde Islands (+238)','phone_code' => '238'),
            array('id' => '35','code' => 'KY','country' => 'Cayman Islands','phone_name' => 'Cayman Islands (+1345)','phone_code' => '1345'),
            array('id' => '36','code' => 'CF','country' => 'Central African Republic','phone_name' => 'Central African Republic (+236)','phone_code' => '236'),
            array('id' => '37','code' => 'CL','country' => 'Chile','phone_name' => 'Chile (+56)','phone_code' => '56'),
            array('id' => '38','code' => 'CN','country' => 'China','phone_name' => 'China (+86)','phone_code' => '86'),
            array('id' => '39','code' => 'CO','country' => 'Colombia','phone_name' => 'Colombia (+57)','phone_code' => '57'),
            array('id' => '40','code' => 'KM','country' => 'Comoros','phone_name' => 'Comoros (+269)','phone_code' => '269'),
            array('id' => '41','code' => 'CG','country' => 'Congo','phone_name' => 'Congo (+242)','phone_code' => '242'),
            array('id' => '42','code' => 'CK','country' => 'Cook Islands','phone_name' => 'Cook Islands (+682)','phone_code' => '682'),
            array('id' => '43','code' => 'CR','country' => 'Costa Rica','phone_name' => 'Costa Rica (+506)','phone_code' => '506'),
            array('id' => '44','code' => 'HR','country' => 'Croatia','phone_name' => 'Croatia (+385)','phone_code' => '385'),
            array('id' => '45','code' => 'CU','country' => 'Cuba','phone_name' => 'Cuba (+53)','phone_code' => '53'),
            array('id' => '46','code' => 'CY','country' => 'Cyprus North','phone_name' => 'Cyprus North (+90392)','phone_code' => '90392'),
            array('id' => '47','code' => 'CY','country' => 'Cyprus South','phone_name' => 'Cyprus South (+357)','phone_code' => '357'),
            array('id' => '48','code' => 'CZ','country' => 'Czech Republic','phone_name' => 'Czech Republic (+42)','phone_code' => '42'),
            array('id' => '49','code' => 'DK','country' => 'Denmark','phone_name' => 'Denmark (+45)','phone_code' => '45'),
            array('id' => '50','code' => 'DJ','country' => 'Djibouti','phone_name' => 'Djibouti (+253)','phone_code' => '253'),
            array('id' => '51','code' => 'DM','country' => 'Dominica','phone_name' => 'Dominica (+1809)','phone_code' => '1809'),
            array('id' => '52','code' => 'DO','country' => 'Dominican Republic','phone_name' => 'Dominican Republic (+1809)','phone_code' => '1809'),
            array('id' => '53','code' => 'EC','country' => 'Ecuador','phone_name' => 'Ecuador (+593)','phone_code' => '593'),
            array('id' => '54','code' => 'EG','country' => 'Egypt','phone_name' => 'Egypt (+20)','phone_code' => '20'),
            array('id' => '55','code' => 'SV','country' => 'El Salvador','phone_name' => 'El Salvador (+503)','phone_code' => '503'),
            array('id' => '56','code' => 'GQ','country' => 'Equatorial Guinea','phone_name' => 'Equatorial Guinea (+240)','phone_code' => '240'),
            array('id' => '57','code' => 'ER','country' => 'Eritrea','phone_name' => 'Eritrea (+291)','phone_code' => '291'),
            array('id' => '58','code' => 'EE','country' => 'Estonia','phone_name' => 'Estonia (+372)','phone_code' => '372'),
            array('id' => '59','code' => 'ET','country' => 'Ethiopia','phone_name' => 'Ethiopia (+251)','phone_code' => '251'),
            array('id' => '60','code' => 'FK','country' => 'Falkland Islands','phone_name' => 'Falkland Islands (+500)','phone_code' => '500'),
            array('id' => '61','code' => 'FO','country' => 'Faroe Islands','phone_name' => 'Faroe Islands (+298)','phone_code' => '298'),
            array('id' => '62','code' => 'FJ','country' => 'Fiji','phone_name' => 'Fiji (+679)','phone_code' => '679'),
            array('id' => '63','code' => 'FI','country' => 'Finland','phone_name' => 'Finland (+358)','phone_code' => '358'),
            array('id' => '64','code' => 'FR','country' => 'France','phone_name' => 'France (+33)','phone_code' => '33'),
            array('id' => '65','code' => 'GF','country' => 'French Guiana','phone_name' => 'French Guiana (+594)','phone_code' => '594'),
            array('id' => '66','code' => 'PF','country' => 'French Polynesia','phone_name' => 'French Polynesia (+689)','phone_code' => '689'),
            array('id' => '67','code' => 'GA','country' => 'Gabon','phone_name' => 'Gabon (+241)','phone_code' => '241'),
            array('id' => '68','code' => 'GM','country' => 'Gambia','phone_name' => 'Gambia (+220)','phone_code' => '220'),
            array('id' => '69','code' => 'GE','country' => 'Georgia','phone_name' => 'Georgia (+7880)','phone_code' => '7880'),
            array('id' => '70','code' => 'DE','country' => 'Germany','phone_name' => 'Germany (+49)','phone_code' => '49'),
            array('id' => '71','code' => 'GH','country' => 'Ghana','phone_name' => 'Ghana (+233)','phone_code' => '233'),
            array('id' => '72','code' => 'GI','country' => 'Gibraltar','phone_name' => 'Gibraltar (+350)','phone_code' => '350'),
            array('id' => '73','code' => 'GR','country' => 'Greece','phone_name' => 'Greece (+30)','phone_code' => '30'),
            array('id' => '74','code' => 'GL','country' => 'Greenland','phone_name' => 'Greenland (+299)','phone_code' => '299'),
            array('id' => '75','code' => 'GD','country' => 'Grenada','phone_name' => 'Grenada (+1473)','phone_code' => '1473'),
            array('id' => '76','code' => 'GP','country' => 'Guadeloupe','phone_name' => 'Guadeloupe (+590)','phone_code' => '590'),
            array('id' => '77','code' => 'GU','country' => 'Guam','phone_name' => 'Guam (+671)','phone_code' => '671'),
            array('id' => '78','code' => 'GT','country' => 'Guatemala','phone_name' => 'Guatemala (+502)','phone_code' => '502'),
            array('id' => '79','code' => 'GN','country' => 'Guinea','phone_name' => 'Guinea (+224)','phone_code' => '224'),
            array('id' => '80','code' => 'GW','country' => 'Guinea - Bissau','phone_name' => 'Guinea - Bissau (+245)','phone_code' => '245'),
            array('id' => '81','code' => 'GY','country' => 'Guyana','phone_name' => 'Guyana (+592)','phone_code' => '592'),
            array('id' => '82','code' => 'HT','country' => 'Haiti','phone_name' => 'Haiti (+509)','phone_code' => '509'),
            array('id' => '83','code' => 'HN','country' => 'Honduras','phone_name' => 'Honduras (+504)','phone_code' => '504'),
            array('id' => '84','code' => 'HK','country' => 'Hong Kong','phone_name' => 'Hong Kong (+852)','phone_code' => '852'),
            array('id' => '85','code' => 'HU','country' => 'Hungary','phone_name' => 'Hungary (+36)','phone_code' => '36'),
            array('id' => '86','code' => 'IS','country' => 'Iceland','phone_name' => 'Iceland (+354)','phone_code' => '354'),
            array('id' => '87','code' => 'IN','country' => 'India','phone_name' => 'India (+91)','phone_code' => '91'),
            array('id' => '88','code' => 'ID','country' => 'Indonesia','phone_name' => 'Indonesia (+62)','phone_code' => '62'),
            array('id' => '89','code' => 'IR','country' => 'Iran','phone_name' => 'Iran (+98)','phone_code' => '98'),
            array('id' => '90','code' => 'IQ','country' => 'Iraq','phone_name' => 'Iraq (+964)','phone_code' => '964'),
            array('id' => '91','code' => 'IE','country' => 'Ireland','phone_name' => 'Ireland (+353)','phone_code' => '353'),
            array('id' => '92','code' => 'IL','country' => 'Israel','phone_name' => 'Israel (+972)','phone_code' => '972'),
            array('id' => '93','code' => 'IT','country' => 'Italy','phone_name' => 'Italy (+39)','phone_code' => '39'),
            array('id' => '94','code' => 'JM','country' => 'Jamaica','phone_name' => 'Jamaica (+1876)','phone_code' => '1876'),
            array('id' => '95','code' => 'JP','country' => 'Japan','phone_name' => 'Japan (+81)','phone_code' => '81'),
            array('id' => '96','code' => 'JO','country' => 'Jordan','phone_name' => 'Jordan (+962)','phone_code' => '962'),
            array('id' => '97','code' => 'KZ','country' => 'Kazakhstan','phone_name' => 'Kazakhstan (+7)','phone_code' => '7'),
            array('id' => '98','code' => 'KE','country' => 'Kenya','phone_name' => 'Kenya (+254)','phone_code' => '254'),
            array('id' => '99','code' => 'KI','country' => 'Kiribati','phone_name' => 'Kiribati (+686)','phone_code' => '686'),
            array('id' => '100','code' => 'KR','country' => 'Korea North','phone_name' => 'Korea North (+850)','phone_code' => '850'),
            array('id' => '101','code' => 'KR','country' => 'Korea South','phone_name' => 'Korea South (+82)','phone_code' => '82'),
            array('id' => '102','code' => 'KW','country' => 'Kuwait','phone_name' => 'Kuwait (+965)','phone_code' => '965'),
            array('id' => '103','code' => 'KG','country' => 'Kyrgyzstan','phone_name' => 'Kyrgyzstan (+996)','phone_code' => '996'),
            array('id' => '104','code' => 'LAO','country' => 'Laos','phone_name' => 'Laos (+856)','phone_code' => '856'),
            array('id' => '105','code' => 'LV','country' => 'Latvia','phone_name' => 'Latvia (+371)','phone_code' => '371'),
            array('id' => '106','code' => 'LB','country' => 'Lebanon','phone_name' => 'Lebanon (+961)','phone_code' => '961'),
            array('id' => '107','code' => 'LS','country' => 'Lesotho','phone_name' => 'Lesotho (+266)','phone_code' => '266'),
            array('id' => '108','code' => 'LR','country' => 'Liberia','phone_name' => 'Liberia (+231)','phone_code' => '231'),
            array('id' => '109','code' => 'LY','country' => 'Libya','phone_name' => 'Libya (+218)','phone_code' => '218'),
            array('id' => '110','code' => 'LI','country' => 'Liechtenstein','phone_name' => 'Liechtenstein (+417)','phone_code' => '417'),
            array('id' => '111','code' => 'LT','country' => 'Lithuania','phone_name' => 'Lithuania (+370)','phone_code' => '370'),
            array('id' => '112','code' => 'LU','country' => 'Luxembourg','phone_name' => 'Luxembourg (+352)','phone_code' => '352'),
            array('id' => '113','code' => 'MO','country' => 'Macao','phone_name' => 'Macao (+853)','phone_code' => '853'),
            array('id' => '114','code' => 'MK','country' => 'Macedonia','phone_name' => 'Macedonia (+389)','phone_code' => '389'),
            array('id' => '115','code' => 'MG','country' => 'Madagascar','phone_name' => 'Madagascar (+261)','phone_code' => '261'),
            array('id' => '116','code' => 'MW','country' => 'Malawi','phone_name' => 'Malawi (+265)','phone_code' => '265'),
            array('id' => '117','code' => 'MY','country' => 'Malaysia','phone_name' => 'Malaysia (+60)','phone_code' => '60'),
            array('id' => '118','code' => 'MV','country' => 'Maldives','phone_name' => 'Maldives (+960)','phone_code' => '960'),
            array('id' => '119','code' => 'ML','country' => 'Mali','phone_name' => 'Mali (+223)','phone_code' => '223'),
            array('id' => '120','code' => 'MT','country' => 'Malta','phone_name' => 'Malta (+356)','phone_code' => '356'),
            array('id' => '121','code' => 'MH','country' => 'Marshall Islands','phone_name' => 'Marshall Islands (+692)','phone_code' => '692'),
            array('id' => '122','code' => 'MQ','country' => 'Martinique','phone_name' => 'Martinique (+596)','phone_code' => '596'),
            array('id' => '123','code' => 'MR','country' => 'Mauritania','phone_name' => 'Mauritania (+222)','phone_code' => '222'),
            array('id' => '124','code' => 'YT','country' => 'Mayotte','phone_name' => 'Mayotte (+269)','phone_code' => '269'),
            array('id' => '125','code' => 'MX','country' => 'Mexico','phone_name' => 'Mexico (+52)','phone_code' => '52'),
            array('id' => '126','code' => 'FM','country' => 'Micronesia','phone_name' => 'Micronesia (+691)','phone_code' => '691'),
            array('id' => '127','code' => 'MD','country' => 'Moldova','phone_name' => 'Moldova (+373)','phone_code' => '373'),
            array('id' => '128','code' => 'MC','country' => 'Monaco','phone_name' => 'Monaco (+377)','phone_code' => '377'),
            array('id' => '129','code' => 'MN','country' => 'Mongolia','phone_name' => 'Mongolia (+976)','phone_code' => '976'),
            array('id' => '130','code' => 'MS','country' => 'Montserrat','phone_name' => 'Montserrat (+1664)','phone_code' => '1664'),
            array('id' => '131','code' => 'MA','country' => 'Morocco','phone_name' => 'Morocco (+212)','phone_code' => '212'),
            array('id' => '132','code' => 'MZ','country' => 'Mozambique','phone_name' => 'Mozambique (+258)','phone_code' => '258'),
            array('id' => '133','code' => 'MM','country' => 'Myanmar','phone_name' => 'Myanmar (+95)','phone_code' => '95'),
            array('id' => '134','code' => 'NA','country' => 'Namibia','phone_name' => 'Namibia (+264)','phone_code' => '264'),
            array('id' => '135','code' => 'NR','country' => 'Nauru','phone_name' => 'Nauru (+674)','phone_code' => '674'),
            array('id' => '136','code' => 'NP','country' => 'Nepal','phone_name' => 'Nepal (+977)','phone_code' => '977'),
            array('id' => '137','code' => 'NL','country' => 'Netherlands','phone_name' => 'Netherlands (+31)','phone_code' => '31'),
            array('id' => '138','code' => 'NC','country' => 'New Caledonia','phone_name' => 'New Caledonia (+687)','phone_code' => '687'),
            array('id' => '139','code' => 'NZ','country' => 'New Zealand','phone_name' => 'New Zealand (+64)','phone_code' => '64'),
            array('id' => '140','code' => 'NI','country' => 'Nicaragua','phone_name' => 'Nicaragua (+505)','phone_code' => '505'),
            array('id' => '141','code' => 'NE','country' => 'Niger','phone_name' => 'Niger (+227)','phone_code' => '227'),
            array('id' => '142','code' => 'NG','country' => 'Nigeria','phone_name' => 'Nigeria (+234)','phone_code' => '234'),
            array('id' => '143','code' => 'NU','country' => 'Niue','phone_name' => 'Niue (+683)','phone_code' => '683'),
            array('id' => '144','code' => 'NF','country' => 'Norfolk Islands','phone_name' => 'Norfolk Islands (+672)','phone_code' => '672'),
            array('id' => '145','code' => 'MP','country' => 'Northern Marianas','phone_name' => 'Northern Marianas (+670)','phone_code' => '670'),
            array('id' => '146','code' => 'NO','country' => 'Norway','phone_name' => 'Norway (+47)','phone_code' => '47'),
            array('id' => '147','code' => 'OM','country' => 'Oman','phone_name' => 'Oman (+968)','phone_code' => '968'),
            array('id' => '148','code' => 'PW','country' => 'Palau','phone_name' => 'Palau (+680)','phone_code' => '680'),
            array('id' => '149','code' => 'PA','country' => 'Panama','phone_name' => 'Panama (+507)','phone_code' => '507'),
            array('id' => '150','code' => 'PG','country' => 'Papua New Guinea','phone_name' => 'Papua New Guinea (+675)','phone_code' => '675'),
            array('id' => '151','code' => 'PY','country' => 'Paraguay','phone_name' => 'Paraguay (+595)','phone_code' => '595'),
            array('id' => '152','code' => 'PE','country' => 'Peru','phone_name' => 'Peru (+51)','phone_code' => '51'),
            array('id' => '153','code' => 'PH','country' => 'Philippines','phone_name' => 'Philippines (+63)','phone_code' => '63'),
            array('id' => '154','code' => 'PL','country' => 'Poland','phone_name' => 'Poland (+48)','phone_code' => '48'),
            array('id' => '155','code' => 'PT','country' => 'Portugal','phone_name' => 'Portugal (+351)','phone_code' => '351'),
            array('id' => '156','code' => 'PR','country' => 'Puerto Rico','phone_name' => 'Puerto Rico (+1787)','phone_code' => '1787'),
            array('id' => '157','code' => 'QA','country' => 'Qatar','phone_name' => 'Qatar (+974)','phone_code' => '974'),
            array('id' => '158','code' => 'RE','country' => 'Reunion','phone_name' => 'Reunion (+262)','phone_code' => '262'),
            array('id' => '159','code' => 'RO','country' => 'Romania','phone_name' => 'Romania (+40)','phone_code' => '40'),
            array('id' => '160','code' => 'RU','country' => 'Russia','phone_name' => 'Russia (+7)','phone_code' => '7'),
            array('id' => '161','code' => 'RW','country' => 'Rwanda','phone_name' => 'Rwanda (+250)','phone_code' => '250'),
            array('id' => '162','code' => 'SM','country' => 'San Marino','phone_name' => 'San Marino (+378)','phone_code' => '378'),
            array('id' => '163','code' => 'ST','country' => 'Sao Tome & Principe','phone_name' => 'Sao Tome & Principe (+239)','phone_code' => '239'),
            array('id' => '164','code' => 'SA','country' => 'Saudi Arabia','phone_name' => 'Saudi Arabia (+966)','phone_code' => '966'),
            array('id' => '165','code' => 'SN','country' => 'Senegal','phone_name' => 'Senegal (+221)','phone_code' => '221'),
            array('id' => '166','code' => 'RS','country' => 'Serbia','phone_name' => 'Serbia (+381)','phone_code' => '381'),
            array('id' => '167','code' => 'SC','country' => 'Seychelles','phone_name' => 'Seychelles (+248)','phone_code' => '248'),
            array('id' => '168','code' => 'SL','country' => 'Sierra Leone','phone_name' => 'Sierra Leone (+232)','phone_code' => '232'),
            array('id' => '169','code' => 'SG','country' => 'Singapore','phone_name' => 'Singapore (+65)','phone_code' => '65'),
            array('id' => '170','code' => 'SK','country' => 'Slovak Republic','phone_name' => 'Slovak Republic (+421)','phone_code' => '421'),
            array('id' => '171','code' => 'SI','country' => 'Slovenia','phone_name' => 'Slovenia (+386)','phone_code' => '386'),
            array('id' => '172','code' => 'SB','country' => 'Solomon Islands','phone_name' => 'Solomon Islands (+677)','phone_code' => '677'),
            array('id' => '173','code' => 'SO','country' => 'Somalia','phone_name' => 'Somalia (+252)','phone_code' => '252'),
            array('id' => '174','code' => 'ZA','country' => 'South Africa','phone_name' => 'South Africa (+27)','phone_code' => '27'),
            array('id' => '175','code' => 'ES','country' => 'Spain','phone_name' => 'Spain (+34)','phone_code' => '34'),
            array('id' => '176','code' => 'LK','country' => 'Sri Lanka','phone_name' => 'Sri Lanka (+94)','phone_code' => '94'),
            array('id' => '177','code' => 'SH','country' => 'St. Helena','phone_name' => 'St. Helena (+290)','phone_code' => '290'),
            array('id' => '178','code' => 'KN','country' => 'St. Kitts','phone_name' => 'St. Kitts (+1869)','phone_code' => '1869'),
            array('id' => '179','code' => 'LC','country' => 'St. Lucia','phone_name' => 'St. Lucia (+1758)','phone_code' => '1758'),
            array('id' => '180','code' => 'SD','country' => 'Sudan','phone_name' => 'Sudan (+249)','phone_code' => '249'),
            array('id' => '181','code' => 'SR','country' => 'Suriname','phone_name' => 'Suriname (+597)','phone_code' => '597'),
            array('id' => '182','code' => 'SZ','country' => 'Swaziland','phone_name' => 'Swaziland (+268)','phone_code' => '268'),
            array('id' => '183','code' => 'SE','country' => 'Sweden','phone_name' => 'Sweden (+46)','phone_code' => '46'),
            array('id' => '184','code' => 'CH','country' => 'Switzerland','phone_name' => 'Switzerland (+41)','phone_code' => '41'),
            array('id' => '185','code' => 'SY','country' => 'Syria','phone_name' => 'Syria (+963)','phone_code' => '963'),
            array('id' => '186','code' => 'TW','country' => 'Taiwan','phone_name' => 'Taiwan (+886)','phone_code' => '886'),
            array('id' => '187','code' => 'TJ','country' => 'Tajikistan','phone_name' => 'Tajikistan (+7)','phone_code' => '7'),
            array('id' => '188','code' => 'TH','country' => 'Thailand','phone_name' => 'Thailand (+66)','phone_code' => '66'),
            array('id' => '189','code' => 'TG','country' => 'Togo','phone_name' => 'Togo (+228)','phone_code' => '228'),
            array('id' => '190','code' => 'TO','country' => 'Tonga','phone_name' => 'Tonga (+676)','phone_code' => '676'),
            array('id' => '191','code' => 'TT','country' => 'Trinidad & Tobago','phone_name' => 'Trinidad & Tobago (+1868)','phone_code' => '1868'),
            array('id' => '192','code' => 'TN','country' => 'Tunisia','phone_name' => 'Tunisia (+216)','phone_code' => '216'),
            array('id' => '193','code' => 'TR','country' => 'Turkey','phone_name' => 'Turkey (+90)','phone_code' => '90'),
            array('id' => '194','code' => 'TM','country' => 'Turkmenistan','phone_name' => 'Turkmenistan (+7)','phone_code' => '7'),
            array('id' => '195','code' => 'TM','country' => 'Turkmenistan','phone_name' => 'Turkmenistan (+993)','phone_code' => '993'),
            array('id' => '196','code' => 'TC','country' => 'Turks & Caicos Islands','phone_name' => 'Turks & Caicos Islands (+1649)','phone_code' => '1649'),
            array('id' => '197','code' => 'TV','country' => 'Tuvalu','phone_name' => 'Tuvalu (+688)','phone_code' => '688'),
            array('id' => '198','code' => 'UG','country' => 'Uganda','phone_name' => 'Uganda (+256)','phone_code' => '256'),
            array('id' => '199','code' => 'UA','country' => 'Ukraine','phone_name' => 'Ukraine (+380)','phone_code' => '380'),
            array('id' => '200','code' => 'AE','country' => 'United Arab Emirates','phone_name' => 'United Arab Emirates (+971)','phone_code' => '971'),
            array('id' => '201','code' => 'UY','country' => 'Uruguay','phone_name' => 'Uruguay (+598)','phone_code' => '598'),
            array('id' => '202','code' => 'UZ','country' => 'Uzbekistan','phone_name' => 'Uzbekistan (+7)','phone_code' => '7'),
            array('id' => '203','code' => 'VU','country' => 'Vanuatu','phone_name' => 'Vanuatu (+678)','phone_code' => '678'),
            array('id' => '204','code' => 'VA','country' => 'Vatican City','phone_name' => 'Vatican City (+379)','phone_code' => '379'),
            array('id' => '205','code' => 'VE','country' => 'Venezuela','phone_name' => 'Venezuela (+58)','phone_code' => '58'),
            array('id' => '206','code' => 'VN','country' => 'Vietnam','phone_name' => 'Vietnam (+84)','phone_code' => '84'),
            array('id' => '207','code' => 'VG','country' => 'Virgin Islands - British','phone_name' => 'Virgin Islands - British (+1284)','phone_code' => '84'),
            array('id' => '208','code' => 'VI','country' => 'Virgin Islands - US','phone_name' => 'Virgin Islands - US (+1340)','phone_code' => '84'),
            array('id' => '209','code' => 'WF','country' => 'Wallis & Futuna','phone_name' => 'Wallis & Futuna (+681)','phone_code' => '681'),
            array('id' => '210','code' => 'YE','country' => 'Yemen','phone_name' => 'Yemen (North)(+969)','phone_code' => '969'),
            array('id' => '211','code' => 'YE','country' => 'Yemen','phone_name' => 'Yemen (South)(+967)','phone_code' => '967'),
            array('id' => '212','code' => 'ZM','country' => 'Zambia','phone_name' => 'Zambia (+260)','phone_code' => '260'),
            array('id' => '213','code' => 'ZW','country' => 'Zimbabwe','phone_name' => 'Zimbabwe (+263)','phone_code' => '263')
        ]);
    }
}
